services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./backend:/app
    restart: unless-stopped

  # Uncomment when client is added
  # client:
  #   build: ./client
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./client:/app
  #   depends_on:
  #     - backend
  #   restart: unless-stopped
